# Generated by Django 5.0.1 on 2024-02-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                ("medication_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="药物名")),
                ("expiration_date", models.DateField(verbose_name="保质期到期日")),
                ("current_quantity", models.IntegerField(verbose_name="当前存储量")),
            ],
        ),
    ]
