# Generated by Django 5.0.1 on 2024-02-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="appointment_datetime",
        ),
        migrations.AddField(
            model_name="appointment",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="hour",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="reason",
            field=models.TextField(null=True),
        ),
    ]
