# Generated by Django 5.0.1 on 2024-02-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0002_remove_appointment_appointment_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="dose",
            field=models.IntegerField(null=True),
        ),
    ]
