# Generated by Django 5.0.1 on 2024-03-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InfusionSeat",
            fields=[
                ("seat_number", models.IntegerField(primary_key=True, serialize=False)),
                ("is_occupied", models.BooleanField(default=False)),
            ],
        ),
    ]
