# Generated by Django 5.0.1 on 2024-03-14 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0003_alter_appointment_dose"),
        ("infusion", "0001_initial"),
        ("user", "0004_nurse"),
    ]

    operations = [
        migrations.CreateModel(
            name="Infusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in_status", models.BooleanField(default=False)),
                ("sit_down_status", models.BooleanField(default=False)),
                (
                    "infusion_status",
                    models.CharField(
                        choices=[
                            ("not_started", "未开始"),
                            ("infusing", "输液中"),
                            ("waiting_for_removal", "待拔针"),
                            ("completed", "输液完成"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointment.appointment",
                    ),
                ),
                (
                    "nurse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.nurse"
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infusion.infusionseat",
                    ),
                ),
            ],
        ),
    ]
