# Generated by Django 5.0.1 on 2024-03-14 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infusion", "0002_infusion"),
        ("user", "0004_nurse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infusion",
            name="nurse",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="user.nurse"
            ),
        ),
    ]
