# Generated by Django 5.0.1 on 2024-03-14 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infusion", "0003_alter_infusion_nurse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infusion",
            name="seat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="infusion.infusionseat",
            ),
        ),
    ]
