# Generated by Django 5.0.1 on 2024-03-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infusion", "0004_alter_infusion_seat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infusion",
            name="infusion_status",
            field=models.CharField(
                choices=[
                    ("not_started", "未开始"),
                    ("infusing", "输液中"),
                    ("waiting_for_removal", "待拔针"),
                    ("completed", "输液完成"),
                    ("cancelled", "已取消"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
    ]
