# Generated by Django 5.0.1 on 2024-02-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                ("doctor_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="医生姓名")),
                (
                    "gender",
                    models.CharField(
                        choices=[("m", "男"), ("f", "女")],
                        default="m",
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                ("age", models.IntegerField(verbose_name="年龄")),
                ("department", models.CharField(max_length=50, verbose_name="科室")),
                ("title", models.CharField(max_length=50, verbose_name="职称")),
                (
                    "info",
                    models.CharField(
                        help_text="不要超过250字", max_length=255, verbose_name="医生介绍"
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(max_length=20, verbose_name="联系电话"),
                ),
                ("account", models.CharField(max_length=50, verbose_name="账号")),
                ("password", models.CharField(max_length=30, verbose_name="密码")),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="患者姓名")),
                (
                    "gender",
                    models.CharField(
                        choices=[("m", "男"), ("f", "女")],
                        default="m",
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                ("age", models.IntegerField(verbose_name="年龄")),
                (
                    "contact_number",
                    models.CharField(max_length=20, verbose_name="联系电话"),
                ),
                ("address", models.CharField(max_length=255, verbose_name="家庭地址")),
                ("account", models.CharField(max_length=50, verbose_name="账号")),
                ("password", models.CharField(max_length=30, verbose_name="密码")),
            ],
        ),
    ]
