# Generated by Django 5.0.1 on 2024-02-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="account",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="account",
        ),
        migrations.AlterField(
            model_name="doctor",
            name="contact_number",
            field=models.CharField(max_length=20, verbose_name="联系电话/账号"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="contact_number",
            field=models.CharField(max_length=20, verbose_name="联系电话/账号"),
        ),
    ]
