# Generated by Django 5.0.1 on 2024-02-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_doctor_account_remove_patient_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="info",
            field=models.CharField(
                default="", help_text="不要超过250字", max_length=255, verbose_name="病人介绍"
            ),
            preserve_default=False,
        ),
    ]
