# Generated by Django 5.0.1 on 2024-03-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_patient_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nurse",
            fields=[
                ("nurse_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="护士姓名")),
                (
                    "gender",
                    models.CharField(
                        choices=[("m", "男"), ("f", "女")],
                        default="m",
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                ("age", models.IntegerField(verbose_name="年龄")),
                ("department", models.CharField(max_length=50, verbose_name="科室")),
                ("title", models.CharField(max_length=50, verbose_name="职称")),
                (
                    "info",
                    models.CharField(
                        help_text="不要超过250字", max_length=255, verbose_name="护士介绍"
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(max_length=20, verbose_name="联系电话/账号"),
                ),
                ("password", models.CharField(max_length=30, verbose_name="密码")),
            ],
        ),
    ]
